services:
  homebank_db:
    image: postgres:latest
    container_name: homebank_database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=homebank_db
      - POSTGRES_USER=hb_admin
      - POSTGRES_PASSWORD=456789321
